version: '3'
services:
  web:
    image: infracloudio/csvserver:latest
    volumes:
      - type: bind
        source: /Users/mayank.srivastava/Desktop/My_Stuffs/DevOps_Stuffs/Shell/inputFile
        target: /csvserver/inputdata
    ports:
    - "9393:9300"
    environment:
    - CSVSERVER_BORDER=Orange