version: '3'
services:
  web:
    image: infracloudio/csvserver:latest
    volumes:
      - type: bind
        source: ./inputFile
        target: /csvserver/inputdata
    ports:
    - "9393:9300"
    environment:
    - CSVSERVER_BORDER=Orange
  service:
    image: prom/prometheus:v2.22.0
    ports: 
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml