global:
  scrape_interval: 5m
  external_labels:
    monitor: 'csvserver-monitor'
scrape_configs:
  - job_name: 'csvserver' 
    metrics_path: '/metrics'
    static_configs: 
      - targets: ['docker.for.mac.localhost:9393']